export const PASTASITES_LOADING = 'PASTASITES_LOADING';
export const ADD_PASTASITES = 'ADD_PASTASITES';
export const PASTASITES_FAILED = 'PASTASITES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const SIDES_LOADING = 'SIDES_LOADING';
export const ADD_SIDES = 'ADD_SIDES';
export const SIDES_FAILED = 'SIDES_FAILED';